---
traefik_cpu_limit: 200m
traefik_mem_limit: 30Mi
traefik_cpu_requests: 100m
traefik_mem_requests: 20Mi
# default edge router is the first node who isn't a master (second kube-node)
# edit traefik_edge_router_nodes list to deploy other nodes as edge-router (specified by nodename)
traefik_edge_router_nodes:
  - "{{ hostvars[groups['kube-node'][1]]['ansible_nodename'] }}"
#  - "node4"
traefik_ingress_controller_subdomain: "traefik.{{ traefik_public_cluster_domain|default(cluster_name) }}"
traefik_kubernetes_dashboard_subdomain: "k8s.{{ traefik_public_cluster_domain|default(cluster_name) }}"
traefik_kibana_logging_subdomain: "kibana.{{ traefik_public_cluster_domain|default(cluster_name) }}"
traefik_kibana_logging_port: 5601