---
- name: "Traefik | Label 'edge-router' nodes"
  command: "{{ bin_dir }}/kubectl label node {{ item }} role=edge-router --overwrite"
  with_items: "{{ traefik_edge_router_nodes }}"

- name: "Traefik | Write traefik config"
  template:
    src: traefik-configmap.yml.j2
    dest: "{{ kube_config_dir }}/traefik-configmap.yaml"
  register: traefik_configmap

- name: "Traefik | Create traefik config"
  command: "{{bin_dir}}/kubectl apply -f {{ kube_config_dir }}/traefik-configmap.yaml"
  run_once: true
  when: traefik_configmap.changed

- name: "Traefik | Write traefik manifests (RBAC)"
  template:
    src: "{{ item }}.yml.j2"
    dest: "{{ kube_config_dir }}/{{ item }}.yaml"
  with_items:
    - "traefik-rbac"
  run_once: true
  when: rbac_enabled

- name: "Traefik | Create traefik Serviceaccount and Clusterrolebinding (RBAC)"
  command: "{{ bin_dir }}/kubectl apply -f {{ kube_config_dir }}/{{ item }}.yaml -n {{ system_namespace }}"
  with_items:
    - "traefik-rbac"
  run_once: true
  when: rbac_enabled

- name: "Traefik | Write traefik daemonset"
  template:
    src: traefik-ds.yml.j2
    dest: "{{ kube_config_dir }}/traefik-ds.yaml"
  register: traefik_ds_manifest

- name: "traefik | Create traefik daemonset"
  command: "{{ bin_dir }}/kubectl apply -f {{ kube_config_dir }}/traefik-ds.yaml -n {{ system_namespace }}"
  run_once: true
  when: traefik_ds_manifest.changed

- name: "Traefik | Write traefik service"
  template:
    src: traefik-service.yml.j2
    dest: "{{ kube_config_dir }}/traefik-service.yaml"
  register: traefik_service_manifest

- name: "traefik | Create traefik service"
  command: "{{ bin_dir }}/kubectl apply -f {{ kube_config_dir }}/traefik-service.yaml -n {{ system_namespace }}"
  run_once: true
  when: traefik_service_manifest.changed

- name: "traefik | Write traefik ingress"
  template:
    src: traefik-ingress.yml.j2
    dest: "{{ kube_config_dir }}/traefik-ingress.yaml"
  register: traefik_ingress_manifest

- name: "traefik | Create traefik ingress"
  command: "{{ bin_dir }}/kubectl apply -f {{ kube_config_dir }}/traefik-ingress.yaml -n {{ system_namespace }}"
  run_once: true
  when: traefik_ingress_manifest.changed

- name: "traefik | Write Kubernetes dashboard ingress"
  template:
    src: kubernetes-dashboard-ingress.yml.j2
    dest: "{{ kube_config_dir }}/kubernetes-dashboard-ingress.yaml"
  register: kubernetes_dashboard_ingress_manifest

- name: "traefik | Create Kubernetes dashboard ingress"
  command: "{{ bin_dir }}/kubectl apply -f {{ kube_config_dir }}/kubernetes-dashboard-ingress.yaml -n {{ system_namespace }}"
  run_once: true
  when: kubernetes_dashboard_ingress_manifest.changed and dashboard_enabled

- name: "traefik | Write Kibana ingress"
  template:
    src: kibana-ingress.yml.j2
    dest: "{{ kube_config_dir }}/kibana-ingress.yaml"
  register: kibana_ingress_manifest

- name: "traefik | Create Kibana ingress"
  command: "{{ bin_dir }}/kubectl apply -f {{ kube_config_dir }}/kibana-ingress.yaml -n {{ system_namespace }}"
  run_once: true
  when: kibana_ingress_manifest.changed and efk_enabled
