---
- name: "Fluentd | Write fluentd config"
  template:
    src: fluentd-configmap.yml.j2
    dest: "{{ kube_config_dir }}/fluentd-configmap.yaml"
  register: fluentd_configmap

- name: "Fluentd | Create fluentd config"
  command: "{{bin_dir}}/kubectl apply -f {{ kube_config_dir }}/fluentd-configmap.yaml"
  run_once: true
  when: fluentd_configmap.changed

- name: "Fluentd | Write fluentd manifests (RBAC)"
  template:
    src: "{{ item }}.yml.j2"
    dest: "{{ kube_config_dir }}/{{ item }}.yaml"
  with_items:
    - "fluentd-rbac"
  run_once: true
  when: rbac_enabled

- name: "Fluentd | Create fluentd Serviceaccount and Clusterrolebinding (RBAC)"
  command: "{{ bin_dir }}/kubectl apply -f {{ kube_config_dir }}/{{ item }}.yaml -n {{ system_namespace }}"
  with_items:
    - "fluentd-rbac"
  run_once: true
  when: rbac_enabled

- name: "Fluentd | Write fluentd daemonset"
  template:
    src: fluentd-ds.yml.j2
    dest: "{{ kube_config_dir }}/fluentd-ds.yaml"
  register: fluentd_ds_manifest

- name: "Fluentd | Create fluentd daemonset"
  command: "{{ bin_dir }}/kubectl apply -f {{ kube_config_dir }}/fluentd-ds.yaml -n {{ system_namespace }}"
  run_once: true
  when: fluentd_ds_manifest.changed
